"""RT4 Manifest S (RT4_RULING_1 Q2 + Q3) — built ONLY from the two committed read-only prod exports, so every guard
value is prod's own:

    discovery_20261004-080150/{discovery.json, manni_snapshot.json}   (Michael, 4 Oct 08:01)
    export41_20261004-134129/export41.json                            (Michael, 4 Oct 13:41)

    python make_manifest_s.py            writes manifest_s.yaml next to this file (and prints a summary)

S1  MANNI DF (7): the 7 lines whose section id and string disagree — the id is re-pointed to the section the string
    names (793-796 -> 64 3MM MILD STEEL FLOOR, 843-845 -> 65 LOAD LOCK RAILS). Guard: the exact current id AND string.
S2  deleted id 41: its 39 lines in 83/84/85 -> 26 SRD DOOR FITTINGS / 15 DRD DOOR FITTINGS / 21 REAR FRAME & FLOOR
    PLATE. id 41 stays deleted.
S3  deleted id 41's own Settings-page draft: its category keys re-keyed by the A2 rule (only keys it holds; its
    snapshot is never touched).
expect_unused_after: [83, 84, 85] — the window then deletes them through Body Templates.
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROD = HERE.parent / "prod"
DISC = PROD / "discovery_20261004-080150"
EXP41 = PROD / "export41_20261004-134129"

DRIFT = {39: 64, 40: 65}                      # MANNI DF: the id's section -> the section the string names
MOVE41 = {83: 26, 84: 15, 85: 21}             # deleted id 41: the Manni name -> the standard name


def _q(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)  # a JSON string is a valid YAML double-quoted scalar


def main() -> int:
    disc = json.loads((DISC / "discovery.json").read_text(encoding="utf-8"))
    snap = json.loads((DISC / "manni_snapshot.json").read_text(encoding="utf-8"))["tables"]
    e41 = json.loads((EXP41 / "export41.json").read_text(encoding="utf-8"))
    secs = {s["id"]: s["name"] for s in disc["sections"]}
    mats = {m["id"]: m["name"] for m in snap["materials"]}
    bodies = {b["id"]: b["name"] for b in disc["bodies"]}

    entries = []
    # S1 — MANNI DF's drift lines, straight from the export's full rows
    for b in sorted(snap["bill_of_materials"], key=lambda r: r["id"]):
        if b["trailer_type_id"] != 7 or b["bom_section_id"] not in DRIFT:
            continue
        target = DRIFT[b["bom_section_id"]]
        assert secs[target] == b["bom_section"], (b["id"], secs[target], b["bom_section"])
        entries.append({"finding": "S1", "body_id": 7, "body": bodies[7], "section": b["bom_section"],
                        "bom_id": b["id"], "line": mats[b["material_id"]],
                        "current": {"id": b["bom_section_id"], "name": b["bom_section"]},
                        "new": {"id": target, "name": secs[target]}})
    assert [e["bom_id"] for e in entries] == [793, 794, 795, 796, 843, 844, 845], [e["bom_id"] for e in entries]

    # S2 — deleted id 41's 39 lines in 83/84/85
    n41 = 0
    for ln in e41["lines"]:
        assert ln["body_id"] == 41 and secs[ln["section_id"]] == ln["section"], ln
        target = MOVE41[ln["section_id"]]
        entries.append({"finding": "S2", "body_id": 41, "body": ln["body"], "section": ln["section"],
                        "bom_id": ln["bom_id"], "line": ln["material"],
                        "current": {"id": ln["section_id"], "name": ln["section"]},
                        "new": {"id": target, "name": secs[target]}})
        n41 += 1
    assert n41 == 39 and not e41["other_bodies"], (n41, e41["other_bodies"])

    # S3 — id 41's draft: only the keys it actually holds
    payload = json.loads(e41["draft41"]["payload"])
    cats = [n for n in payload["nodes"].values() if isinstance(n, dict) and n.get("type") == "category"]
    drafts = []
    for old_id, new_id in MOVE41.items():
        old, new = secs[old_id], secs[new_id]
        n_old = sum(1 for n in cats if (n.get("sourceCategoryKey") or "").strip().upper() == old.upper())
        n_new = sum(1 for n in cats if (n.get("sourceCategoryKey") or "").strip().upper() == new.upper())
        assert n_new == 0, (new, n_new)       # the A2 rule would leave it; S would then not list it
        if n_old:
            drafts.append({"finding": "S3", "body_id": 41, "body": bodies[41], "old_key": old, "new_key": new,
                           "nodes": n_old})
    assert e41["drafts_naming_old"] == [{"body_id": 41, "keys": sorted(d["old_key"] for d in drafts)}], \
        e41["drafts_naming_old"]

    out = [
        "# RT4 Manifest S (RT4_RULING_1 Q2 + Q3). GENERATED by make_manifest_s.py from the committed read-only prod",
        "# exports (discovery_20261004-080150, export41_20261004-134129) — do not hand-edit; re-run the generator.",
        "# Tool: backend/tools/audit_pricing_corrections.py (field: section = bom_section_id + bom_section together;",
        "# drafts: the A2 rule; expect_unused_after: a STOP if anything else still names those sections).",
        f"note: {_q('v1.60.1 RT4 Manifest S — MANNI DF section drift + deleted id 41 off the Manni section names')}",
        "expect_unused_after: [83, 84, 85]",
        "changes:",
    ]
    for e in entries:
        out += [f"  - finding: {e['finding']}",
                f"    body_id: {e['body_id']}",
                f"    body: {_q(e['body'])}",
                f"    section: {_q(e['section'])}",
                f"    bom_id: {e['bom_id']}",
                f"    line: {_q(e['line'])}",
                "    field: section",
                f"    current: {{id: {e['current']['id']}, name: {_q(e['current']['name'])}}}",
                f"    new: {{id: {e['new']['id']}, name: {_q(e['new']['name'])}}}"]
    out.append("drafts:")
    for d in drafts:
        out += [f"  - finding: {d['finding']}",
                f"    body_id: {d['body_id']}",
                f"    body: {_q(d['body'])}",
                f"    old_key: {_q(d['old_key'])}",
                f"    new_key: {_q(d['new_key'])}",
                f"    nodes: {d['nodes']}"]
    (HERE / "manifest_s.yaml").write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    by = {}
    for e in entries:
        by.setdefault((e["finding"], e["current"]["name"], e["new"]["name"]), []).append(e["bom_id"])
    for (f, a, b), ids in sorted(by.items()):
        print(f"{f}  {len(ids):>2} line(s)  {a!r} -> {b!r}  bom {ids}")
    for d in drafts:
        print(f"{d['finding']}  draft of body {d['body_id']}: {d['old_key']!r} -> {d['new_key']!r} ({d['nodes']} node)")
    print(f"total: {len(entries)} line changes + {len(drafts)} draft re-keys")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
